### ISSUE TITLE
LLamar a Sra. Ochoa

### ISSUE THREAD

**Issue by smbantjes** [mfrasca/ghini-inception#10]
Llamar a Sra. Ochoa
- Cita con Memo pero hasta ahora no he llegado (la tiera, la casa>>>>)

**Comment by mfrasca** [comment]
he llamado a ambos y no entiendo lo que pasa. Memo me deja llegar a la contestadora y no me devuelve las llamadas, la señora me dice que Memo está enfermo, Teo al revés me comentó que Memo está bien y trabajando...
