### ISSUE TITLE
Proyecto de manglar CARSUCRE y Fusabana

### ISSUE THREAD

**Issue by smbantjes** [mfrasca/ghini-inception#11]
Hablar sobre proyecto de manglar (2002) CARSURCRE y Fusabana

Objetivo del Projecto, Manera de motivar personas,actividades, resultados, estan todavia trabajando recuperar el mangle

Luis Eduardo Julio y Honorio Guerra

**Comment by mfrasca** [comment]
Ruby no conoce a LEJ, pero sí a HG. nunca escuchó el nombre 'fusabana'. HG se ha trasladado a Tolú.
