### ISSUE TITLE
BG recorder 2 phone Alberto Gomez Mejia

### ISSUE THREAD

**Issue by smbantjes** [mfrasca/ghini-inception#7]
Phone Alberto Gomez Mejia from red de Jardin Botancio en Colombia and find out if BG recorder data base system is still used. Maybe new update? 
Maybe he can give also some advise on fundraising possibilities for Cuchubo garden.

57 3102127510 or 57 16608136

**Comment by mfrasca** [comment]
acabo de hablar con una señora Catarina probablemente Sofroni, de la RNJB, el señor Alberto no se encontraba pero esta joven tenía toda la información necesaria y parecía entender muy bien mis preguntas y todo de que estaba hablando.

me dijo: 
- el software es "closed source" y está basado en MS-access
- los usuarios ven el software como excesivo y muchos jardines tienen colecciones en excel.
- desde el 2002 no se hizo ninguna actualización del software.
- la RNJB no tiene capacidad de análisis de software.
- están pensando adoptar otro (Babilonia) pero no tienen recursos económicos para considerar la opción.
- el Humboldt (que se ocupa de colecciones biológicas) no tiene software que maneje jardines.

le expliqué de la idea del proyecto en Mompox, y que un efecto colateral del proyecto podría ser producir un software de gestión de jardines botánicos y me dijo que le parecía interesante, se anotó mi correo y me prometió que me van a enviar un correo para cuadrar una cita en vídeo y hablar en skype con Alberto.

**Comment by mfrasca** [comment]
de que todavía no se alcanza a hacer nada. están evaluando opciones. de Mompox salió Bauble puesto al día, y el protótipo de Ghini, de que a Carolina Sofrony (ahora la jefa de la RNJB) no parecen interesar.
